server:
  port: 4211
spring:
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto=create:

management:
  endpoints:
    web:
      exposure:
        include: health,loggers

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/patrimonio
    driver: com.mysql.jdbc.Driver
    username: root
    password:
    jpa:
      properties:
        hibernate:
          default_schema: Patrimonio
    logging:
      level:
        root: WARN






#-- patrimonio.TB_AREA definition
#
#CREATE TABLE `TB_AREA` (
#  `ID` int NOT NULL,
#  `NOME_AREA` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
#  `TIPO_AREA` int DEFAULT NULL,
#  PRIMARY KEY (`ID`)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


#
#  CREATE TABLE `TB_LISTA` (
#  `ID` int NOT NULL,
#  `ID_AREA` int DEFAULT NULL,
#  `ID_USUARIO` int DEFAULT NULL,
#  `ID_PATRIMONIO` int DEFAULT NULL,
#  KEY `TB_LISTA_FK_1` (`ID`),
#  KEY `TB_LISTA_FK` (`ID_AREA`),
#  KEY `TB_LISTA_FK_2` (`ID_PATRIMONIO`),
#  CONSTRAINT `TB_LISTA_FK` FOREIGN KEY (`ID_AREA`) REFERENCES `TB_AREA` (`ID`),
#  CONSTRAINT `TB_LISTA_FK_1` FOREIGN KEY (`ID`) REFERENCES `TB_USUARIO` (`ID`),
#  CONSTRAINT `TB_LISTA_FK_2` FOREIGN KEY (`ID_PATRIMONIO`) REFERENCES `TB_PATRIMONIO` (`CODIGO`)
#  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


#-- patrimonio.TB_PATRIMONIO definition
#
#CREATE TABLE `TB_USUARIO` (
#  `ID` int NOT NULL,
#  `PRONTUARIO` varchar(100) NOT NULL,
#  `NOME` varchar(100) DEFAULT NULL,
#  `SENHA` varchar(45) DEFAULT NULL,
#  `NIVELACESSO` int DEFAULT NULL,
#  PRIMARY KEY (`ID`)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



#CREATE TABLE `TB_USUARIO` (
#  `ID` int NOT NULL,
#  `PRONTUARIO` varchar(100) NOT NULL,
#  `NOME` varchar(100) DEFAULT NULL,
#  `SENHA` varchar(45) DEFAULT NULL,
#  `NIVELACESSO` int DEFAULT NULL,
#  PRIMARY KEY (`ID`)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;